import { Inter } from "next/font/google";
import "./globals.css";
import SingleVehicleContextProvider from "../context/SingleVehicalContextProvider";
import Footer from "@/components/Footer";
import AbsoluteFooter from "@/components/AbsoluteFooter";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SingleVehicleContextProvider>
          <Navbar/>
          {children}
          <Footer />
          <AbsoluteFooter/>
        </SingleVehicleContextProvider>
      </body>
    </html>
  );
}
