import { Inter } from "next/font/google";
import "./globals.css";

import AbsoluteFooter from "@/components/AbsoluteFooter";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TourContextProvider from "../context/TourContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TourContextProvider>
          <div className=" relative flex flex-col min-h-[100vh] ">
            <NavBar />

            <main className=" mt-[100px] mobile:mt-[120px] ">{children}</main>

            <Footer />
            <AbsoluteFooter />
          </div>
        </TourContextProvider>
      </body>
    </html>
  );
}
