import { Inter } from "next/font/google";
import "./globals.css";
import SingleVehicleContextProvider from "../context/SingleVehicalContextProvider";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SingleVehicleContextProvider>
          <Navigation />
          {children}
          <Footer />
        </SingleVehicleContextProvider>
      </body>
    </html>
  );
}
